### ISSUE TITLE
Can't load module oc.lazyLoad

### ISSUE THREAD

**Issue by mlwils0** [ocombe/ocLazyLoad#132]
"data" variable, in "signature" function, is null:
        var signature = function (data) {
            if (angular.isArray(data)) { // arrays are objects, we need to test for it first
                return data.toString();
            } else if (angular.isObject(data)) { // constants & values for example
                return JSON.stringify(data);
            } else {
                return data.toString(); <----------------------This is where the error occurs
            }
        };

StackTrace: 
Uncaught Error: [$injector:modulerr] Failed to instantiate module admin_module due to:
Error: [$injector:modulerr] Failed to instantiate module oc.lazyLoad due to:
TypeError: Cannot read property 'toString' of null
    at signature (http://localhost:51983/Scripts/ocLazyLoad.js:859:28)
    at registerInvokeList (http://localhost:51983/Scripts/ocLazyLoad.js:866:66)
    at invokeQueue (http://localhost:51983/Scripts/ocLazyLoad.js:755:29)
    at addReg (http://localhost:51983/Scripts/ocLazyLoad.js:948:17)
    at Object.forEach (http://localhost:51983/Scripts/angular.js:323:20)
    at addReg (http://localhost:51983/Scripts/ocLazyLoad.js:951:25)
    at Object.forEach (http://localhost:51983/Scripts/angular.js:323:20)
    at addReg (http://localhost:51983/Scripts/ocLazyLoad.js:951:25)
    at http://localhost:51983/Scripts/ocLazyLoad.js:956:13
    at Object.forEach (http://localhost:51983/Scripts/angular.js:323:20)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=oc.lazyLoad&p1=Typ…orEach%20(http%3A%2F%2Flocalhost%3A51983%2FScripts%2Fangular.js%3A323%3A20)
    at http://localhost:51983/Scripts/angular.js:63:12
    at http://localhost:51983/Scripts/angular.js:4120:15
    at forEach (http://localhost:51983/Scripts/angular.js:323:20)
    at loadModules (http://localhost:51983/Scripts/angular.js:4081:5)
    at http://localhost:51983/Scripts/angular.js:4098:40
    at forEach (http://localhost:51983/Scripts/angular.js:323:20)
    at loadModules (http://localhost:51983/Scripts/angular.js:4081:5)
    at createInjector (http://localhost:51983/Scripts/angular.js:4007:11)
    at doBootstrap (http://localhost:51983/Scripts/angular.js:1445:20)
    at bootstrap (http://localhost:51983/Scripts/angular.js:1466:12)

**Comment by ocombe** [comment]
Thanks for the report, I've already changed this function in my next new version, so this shouldn't be a problem any longer once I'm done with the new code.

**Comment by ocombe** [comment]
This is fixed in https://github.com/ocombe/ocLazyLoad/commit/83d416f97d357d148efe97bafbaf2836ed7b3a3d

**Comment by ocombe** [comment]
It should be fixed in 0.6.0!
